--- #YAML:1.0
name:                Image-Match
version:             1.01
abstract:            locate image inside another
license:             ~
author:              
    - Dmitry Karasik <dmitry@karasik.eu.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Prima:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
